version: '3.9'

services:
  go-app:
    container_name: go-app
    build: .
    environment:
      ENV: docker
    ports:
      - "3000:3000"
    depends_on:
      - go_db
    networks:
      - fullstack
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: real_estate
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:  
  pgdata: {}

networks:
  fullstack:
    driver: bridge